name: Generate and execute Diagrams python script

on:
  workflow_dispatch:
    inputs:
      mermaid_script:
        description: 'Mermaid Script'
        required: true
 
jobs:
 
  generate_diagrams_code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.ACTIONS_PAT_TOKEN }}
        
        
    - name: Install dependencies
      run: |
        echo "${{ github.event.inputs.mermaid_script }}"
        pip install -r requirements.txt
        sudo apt-get install graphviz
        ls -a
        # cd temp_src_images
        # pwd
        # cd ..
        echo "${{ github.event.inputs.mermaid_script }}" > mermaid.html
        python archimagen.py -m "$(cat mermaid.html)"
        # cat dynamic_diagrams_code.py
        cd dynamically_generated_stuff
        rm -rf temp_src_images/*
        rm -rf architecture_diagram.png
        python dynamic_diagrams_code.py
        
        git config user.email "winadm1n@protonmail.com"
        git config user.name "winadm1n"
        git add .
        git commit -m "Move files to new folder"
        git push origin main
