name: Generate and execute Diagrams python script

on:
  workflow_dispatch:
    inputs:
      mermaid_script:
        description: 'Mermaid Script'
        required: true
        default : "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Generated Architecture</title>\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.css\">\n</head>\n<body>\n    <div class=\"mermaid\">\n        graph LR\n        A[Text Data] --> B[Azure Cognitive Services]\n        B --> C[Sentiment Analysis]\n        C --> D[Sentiment Score]\n        D --> E[Positive/Negative Result]\n    </div>\n    <script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\n    <script>\n        mermaid.initialize({\n                        startOnLoad: true\n                    });\n    </script>\n</body>\n</html>"
 
 
jobs:
 
  generate_diagrams_code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.ACTIONS_PAT_TOKEN }}
        
        
    - name: Install dependencies
      run: |
        echo "${{ github.event.inputs.mermaid_script }}"
        python --version
        pip install -r requirements.txt
        ls -a
        python archimagen.py -m "${{ github.event.inputs.mermaid_script }}"
        # python -m pip install --upgrade pip
        # pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    


    # - name: print_input
    #   run: |
    #     javac *.java
    #   working-directory: ./migrated-${{ github.event.inputs.mermaid_script }}/src
